spring:
  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 테스트용은 create, 운영은 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  profiles:
    active: local


# JWT 설정 추가
jwt:
  secret: ${JWT_SECRET} # 환경변수에서 가져오기
  token-validity-in-seconds: ${JWT_VALIDITY:86400} # 기본 24시간

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
