spring:
  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost:3307/daangn
#    username: ssafy
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 개발 중에는 update, 테스트용은 create, 운영은 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  profiles:
    active: local

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
