version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: daangn-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0307
      MYSQL_DATABASE: daangn
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-daangn:latest
    container_name: daangn-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # DataSource 설정
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/daangn?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: ssafy
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # JPA 설정
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      # JWT 설정
      JWT_SECRET: IFTHEWORLDWASENDINGIDWANNABENEXTTOYOU
      JWT_ACCESS_TOKEN_EXPIRATION: 3600000
      JWT_REFRESH_TOKEN_EXPIRATION: 1209600000

volumes:
  db_data:
