version: '3'
services:
  app:
    build: .
    container_name: spring-daangn
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always
