spring:
  config:
    import: optional:file:dev.env[.properties]

  datasource:
    url: ${DB_URL} #jdbc:mysql://localhost:3306/daangn
    username: ${DB_USERNAME} #"ssafy"
    password: ${DB_PASSWORD} #"ssafy"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug