spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true # 콘솔에 SQL 보여줌
    open-in-view: false # 성능상 좋음

  # 웹 인코딩 설정
  mvc:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  web:
    locale: ko

# JWT 설정
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForSecurity123}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}    # 1시간 (1000 * 60 * 60)
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (1000 * 60 * 60 * 24 * 7)

logging:
  level:
    org.hibernate.SQL: debug             # SQL 문장 출력
    org.hibernate.type.descriptor.sql: trace  # 바인딩 값까지 출력
    org.springframework.boot.context.config: DEBUG
    org.springframework.security: DEBUG  # Spring Security 로그 (JWT 디버깅용)
    com.ssafy.spring_boot.security: DEBUG # 우리 보안 패키지 로그