spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daangn?createDatabaseIfNotExist=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
