spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daangn?createDatabaseIfNotExist=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug # 실행되는 SQL 쿼리 출력
    org.hibernate.orm.jdbc.bind: trace # SQL 쿼리 파라미터 출력
    org.example.springboot.service: debug # 서비스 레이어 로깅

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: TVHH28SHOICF0iwejO5N/tE9qSpzc0BmcsWxF91KdWvjtWjvThzMtZc2Vt0WTM82nWQHbONUzwDrC2Svzf7i8w==
  access-token:
    expiration: 3600000  # 1시간 (밀리초)
  refresh-token:
    expiration: 604800000  # 7일 (밀리초)