spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true # 콘솔에 SQL 보여줌
    open-in-view: false # 성능상 좋음
logging:
  level:
    org.hibernate.SQL: debug             # SQL 문장 출력
    org.hibernate.type.descriptor.sql: trace  # 바인딩 값까지 출력
  # ?? ?? ?? ?? (?? ?)
  mvc:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  web:
    locale: ko
